spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/Aviatickets?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 20
      driver-class-name: org.postgresql.Driver
    username: development
    password: dev
    url: "jdbc:postgresql://localhost:5432/Aviatickets?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver

---